# Generated by Django 3.2.8 on 2021-11-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True, verbose_name='Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, unique=True, verbose_name='Magasin')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Produit')),
                ('product_image', models.URLField(null=True)),
                ('product_image_little', models.URLField(null=True)),
                ('brand', models.TextField(null=True, verbose_name='Marque')),
                ('description', models.TextField(null=True)),
                ('nutriscore', models.CharField(max_length=1)),
                ('fat', models.CharField(default='NC', max_length=30)),
                ('saturated_fat', models.CharField(default='NC', max_length=30)),
                ('salt', models.CharField(default='NC', max_length=30)),
                ('sugar', models.CharField(default='NC', max_length=30)),
                ('url', models.URLField(null=True)),
                ('category', models.ManyToManyField(to='Product.Category')),
                ('store', models.ManyToManyField(to='Product.Store')),
            ],
        ),
    ]
