# Generated by Django 3.2.8 on 2021-10-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bad_product', to='Product.product', verbose_name='Produit ')),
                ('substitute_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Product.product', verbose_name='Substitut')),
            ],
        ),
    ]
